name: Deploy NGINX to EKS using Helm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure AWS credentials using access keys
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Verify identity (optional)
      - name: Verify AWS identity
        run: aws sts get-caller-identity

      # Update kubeconfig for EKS cluster
      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ap-south-1 --name demo-eks
          kubectl get nodes

      # Set up Helm
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      # Deploy app using Helm
      - name: Deploy NGINX with Helm
        run: |
          helm upgrade --install my-nginx ./helm/my-nginx \
            --namespace dev \
            -f ./helm/my-nginx/dev-values.yaml

      # Verify pods
      - name: Verify deployment
        run: kubectl get all -n dev
