name: infra-setup

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: "Choose Terraform action (apply or destroy)"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy
 
jobs:
  setup-infra: 
    runs-on: ubuntu-latest

    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
             
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init 

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format
        run: terraform fmt -recursive  

      - name: Terraform Plan
        run: terraform plan

      # ✅ Unified step for Apply or Destroy
      - name: Terraform Apply/Destroy
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            action="${{ github.event.inputs.action }}"
          else
            action="apply"
          fi

          echo "Selected action: $action"

          if [ "$action" = "destroy" ]; then
            terraform destroy -auto-approve
          else
            terraform apply -auto-approve
          fi
