name: infra-setup

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  setup-infra: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
             