name: infra-setup

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  setup-infra: 
    runs-on: ubuntu-latest

    permissions: 
      id-token: write
      contents: read


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
             
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init 

      - name: Terraform validate
        run: terraform validate

      - name: Terraform format
        run: terraform fmt -recursive  

      - name: Terraform plan
        run: terraform plan 

      - name: Terraform apply
        run: terraform apply -auto-approve  


